export const ACTION_TYPE = {
  LOGOUT: "LOGOUT",
  ON_OPEN_MODAL: "ON_OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_USER: "SET_USER",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CHANGE_USER: "SET_CHANGE_USER,",
  SET_USERS: "SET_USERS",
  ADD_PRODUCT_TO_BASKET: "ADD_PRODUCT_TO_BASKET",
  SET_CHANGE_PRODUCTS: "SET_CHANGE_PRODUCTS,",
  REMOVE_PRODUCT_FROM_BASKET: "REMOVE_PRODUCT_FROM_BASKET",
  SET_PRODUCTS_FROM_BASKET: "SET_PRODUCTS_FROM_BASKET",
};
